// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // El CLI (migrate/db push) necesita conexion directa, sin pooler (PgBouncer no soporta
    // bien las sentencias DDL de las migraciones). La app en runtime usa DATABASE_URL
    // (pooled) via el adaptador en lib/db.ts, no este valor.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
